"""Update row Command in sales table 

Revision ID: 288064138f16
Revises: 01a4bdd4a9b5
Create Date: 2024-06-14 17:39:14.402514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '288064138f16'
down_revision: Union[str, None] = '01a4bdd4a9b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'order_status',
               existing_type=mysql.TINYINT(),
               comment=" '0:Waiting', '1:Confirmed','2:Shipped', '3:Delivered' ",
               existing_comment=" '0:Waiting', '1:Confirm', '2:Delivery' ",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'order_status',
               existing_type=mysql.TINYINT(),
               comment=" '0:Waiting', '1:Confirm', '2:Delivery' ",
               existing_comment=" '0:Waiting', '1:Confirmed','2:Shipped', '3:Delivered' ",
               existing_nullable=True)
    # ### end Alembic commands ###
