"""Salesdetails table create

Revision ID: 3194082290c2
Revises: 7e6e125c848b
Create Date: 2024-06-14 10:57:01.960152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3194082290c2'
down_revision: Union[str, None] = '7e6e125c848b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('user_type', mysql.TINYINT(), nullable=True, comment='1->Admin,2->superAdmin,3->Employee,4->customer'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'user_type')
    # ### end Alembic commands ###
