"""update_date row create in stock table 

Revision ID: 4520a48ce15b
Revises: 7e10ce2f10f6
Create Date: 2024-06-14 15:17:57.577483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4520a48ce15b'
down_revision: Union[str, None] = '7e10ce2f10f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('update_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'update_date')
    # ### end Alembic commands ###
