"""Update row Command in sales table 

Revision ID: 480ef15a2868
Revises: 288064138f16
Create Date: 2024-06-14 17:55:11.085905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '480ef15a2868'
down_revision: Union[str, None] = '288064138f16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'user_type',
               existing_type=mysql.TINYINT(),
               comment='1->SuperAdmin,2->Admin,3->Employee,4->customer',
               existing_comment='1->Admin,2->superAdmin,3->Employee,4->customer',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'user_type',
               existing_type=mysql.TINYINT(),
               comment='1->Admin,2->superAdmin,3->Employee,4->customer',
               existing_comment='1->SuperAdmin,2->Admin,3->Employee,4->customer',
               existing_nullable=True)
    # ### end Alembic commands ###
