"""order_status row create in sales table 

Revision ID: 6a585bd7df0f
Revises: 6c4b98ffc3b2
Create Date: 2024-06-14 14:46:33.275682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a585bd7df0f'
down_revision: Union[str, None] = '6c4b98ffc3b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
