"""order_status row create in sales table 

Revision ID: 6c4b98ffc3b2
Revises: 3194082290c2
Create Date: 2024-06-14 14:45:45.364509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6c4b98ffc3b2'
down_revision: Union[str, None] = '3194082290c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('order_status', mysql.TINYINT(), nullable=True, comment=" '0:Waiting', '1:Confirm', '2:Delivery' "))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'order_status')
    # ### end Alembic commands ###
