"""order_status row create in sales table 

Revision ID: 7e10ce2f10f6
Revises: 6a585bd7df0f
Create Date: 2024-06-14 14:49:47.805050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7e10ce2f10f6'
down_revision: Union[str, None] = '6a585bd7df0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('order_status', mysql.TINYINT(), nullable=True, comment=" '0:Waiting', '1:Confirm', '2:Delivery' "))
    op.drop_column('stock', 'order_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('order_status', mysql.TINYINT(), autoincrement=False, nullable=True, comment=" '0:Waiting', '1:Confirm', '2:Delivery' "))
    op.drop_column('sales', 'order_status')
    # ### end Alembic commands ###
