"""Salesdetails table create

Revision ID: 7e6e125c848b
Revises: d3788a5a22c6
Create Date: 2024-06-10 17:24:12.411657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7e6e125c848b'
down_revision: Union[str, None] = 'd3788a5a22c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salesdetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment=" '1:Active', '-1:Inactive', '0:Delete' "),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['sales_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sales', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.add_column('sales', sa.Column('address', sa.String(length=70), nullable=True))
    op.add_column('sales', sa.Column('postal_code', sa.Integer(), nullable=True))
    op.add_column('sales', sa.Column('payment_type', sa.String(length=50), nullable=True))
    op.drop_constraint('sales_ibfk_2', 'sales', type_='foreignkey')
    op.drop_constraint('sales_ibfk_1', 'sales', type_='foreignkey')
    op.create_foreign_key(None, 'sales', 'customer', ['customer_id'], ['id'])
    op.drop_column('sales', 'cus_id')
    op.drop_column('sales', 'qty')
    op.drop_column('sales', 'rate')
    op.drop_column('sales', 'pro_id')
    op.add_column('stock', sa.Column('product_id', sa.Integer(), nullable=True))
    op.add_column('stock', sa.Column('quantity', sa.Integer(), nullable=True))
    op.drop_constraint('stock_ibfk_1', 'stock', type_='foreignkey')
    op.create_foreign_key(None, 'stock', 'product', ['product_id'], ['id'])
    op.drop_column('stock', 'qty')
    op.drop_column('stock', 'pro_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('pro_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stock', sa.Column('qty', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'stock', type_='foreignkey')
    op.create_foreign_key('stock_ibfk_1', 'stock', 'product', ['pro_id'], ['id'])
    op.drop_column('stock', 'quantity')
    op.drop_column('stock', 'product_id')
    op.add_column('sales', sa.Column('pro_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sales', sa.Column('rate', mysql.FLOAT(), nullable=True))
    op.add_column('sales', sa.Column('qty', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sales', sa.Column('cus_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.create_foreign_key('sales_ibfk_1', 'sales', 'customer', ['cus_id'], ['id'])
    op.create_foreign_key('sales_ibfk_2', 'sales', 'product', ['pro_id'], ['id'])
    op.drop_column('sales', 'payment_type')
    op.drop_column('sales', 'postal_code')
    op.drop_column('sales', 'address')
    op.drop_column('sales', 'customer_id')
    op.drop_table('salesdetails')
    # ### end Alembic commands ###
