"""EXPIRE_AT  row create in apitoken table 

Revision ID: 905e167e7cd6
Revises: c7d33ae3ee12
Create Date: 2024-06-15 15:23:38.194518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '905e167e7cd6'
down_revision: Union[str, None] = 'c7d33ae3ee12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.add_column('wishlist', sa.Column('product_id', sa.Integer(), nullable=True))
    op.drop_constraint('wishlist_ibfk_2', 'wishlist', type_='foreignkey')
    op.drop_constraint('wishlist_ibfk_1', 'wishlist', type_='foreignkey')
    op.create_foreign_key(None, 'wishlist', 'customer', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'wishlist', 'product', ['product_id'], ['id'])
    op.drop_column('wishlist', 'cus_id')
    op.drop_column('wishlist', 'pro_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist', sa.Column('pro_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('wishlist', sa.Column('cus_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'wishlist', type_='foreignkey')
    op.drop_constraint(None, 'wishlist', type_='foreignkey')
    op.create_foreign_key('wishlist_ibfk_1', 'wishlist', 'customer', ['cus_id'], ['id'])
    op.create_foreign_key('wishlist_ibfk_2', 'wishlist', 'product', ['pro_id'], ['id'])
    op.drop_column('wishlist', 'product_id')
    op.drop_column('wishlist', 'customer_id')
    # ### end Alembic commands ###
