"""EXPIRE_AT  row create in apitoken table 

Revision ID: c7d33ae3ee12
Revises: 4b9cddddce6c
Create Date: 2024-06-15 15:20:51.340581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c7d33ae3ee12'
down_revision: Union[str, None] = '4b9cddddce6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_tokens', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('cart', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.add_column('cart', sa.Column('product_id', sa.Integer(), nullable=True))
    op.drop_constraint('cart_ibfk_2', 'cart', type_='foreignkey')
    op.drop_constraint('cart_ibfk_1', 'cart', type_='foreignkey')
    op.create_foreign_key(None, 'cart', 'customer', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'cart', 'product', ['product_id'], ['id'])
    op.drop_column('cart', 'pro_id')
    op.drop_column('cart', 'cus_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('cus_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cart', sa.Column('pro_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key('cart_ibfk_1', 'cart', 'customer', ['cus_id'], ['id'])
    op.create_foreign_key('cart_ibfk_2', 'cart', 'product', ['pro_id'], ['id'])
    op.drop_column('cart', 'product_id')
    op.drop_column('cart', 'customer_id')
    op.drop_column('api_tokens', 'expires_at')
    # ### end Alembic commands ###
