"""user name not a unique

Revision ID: d3788a5a22c6
Revises: d49109bac1f5
Create Date: 2024-06-05 17:31:00.097290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3788a5a22c6'
down_revision: Union[str, None] = 'd49109bac1f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('first_name', table_name='customer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('first_name', 'customer', ['first_name'], unique=True)
    # ### end Alembic commands ###
