"""date

Revision ID: d49109bac1f5
Revises: a8a1275ee46e
Create Date: 2024-06-05 11:59:11.423546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd49109bac1f5'
down_revision: Union[str, None] = 'a8a1275ee46e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('customer', sa.Column('phone_number', sa.String(length=12), nullable=True))
    # op.drop_index('mobile_number', table_name='customer')
    # op.create_unique_constraint(None, 'customer', ['phone_number'])
    # op.drop_column('customer', 'mobile_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('customer', sa.Column('mobile_number', mysql.VARCHAR(length=12), nullable=True))
    op.drop_constraint(None, 'customer', type_='unique')
    # op.create_index('mobile_number', 'customer', ['mobile_number'], unique=True)
    op.drop_column('customer', 'phone_number')
    # ### end Alembic commands ###
